color0 #46464c
color1 #ffb4ab
color2 #c1c5dd
color3 #c5c6d0
color4 #dcbed2
color5 #c1c5dd
color6 #c5c6d0
color7 #e5e2e3
color8 #909097
color9 #ffb4ab
color10 #c1c5dd
color11 #c5c6d0
color12 #dcbed2
color13 #c1c5dd
color14 #c5c6d0
color15 #e5e2e3

cursor                #e5e2e3
cursor_text_color     #131315
background            #131315
foreground            #e5e2e3
selection_foreground  #c7c6cd
selection_background  #46464c
active_border_color   #c1c5dd
inactive_border_color #46464c
url_color             #c1c5dd

active_tab_foreground   #2b3042
active_tab_background   #c1c5dd
inactive_tab_foreground #c7c6cd
inactive_tab_background #46464c
cursor_trail_color      #c7c6cd
